name: Build Deb Package

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: ["published"]
jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Build Debian Package in Docker
        run: |
          docker run --rm -v $(pwd):/tmp debian:bullseye-slim bash -c \
          "cd /tmp \
          && chmod 555 vioneta-supervised/DEBIAN/p* \
          && dpkg-deb --build --root-owner-group vioneta-supervised"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vioneta-supervised.deb
